import React from 'react'
import {
  AlertTriangle,
  Apple,
  Archive,
  Armchair,
  ArrowDownFromLine,
  ArrowRightLeft,
  ArrowUpFromLine,
  Baby,
  Balloon,
  Banknote,
  BarChart3,
  Beef,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  BrushCleaning,
  Bug,
  Building2,
  CakeSlice,
  Calendar,
  Car,
  CarTaxiFront,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  Church,
  CircleDollarSign,
  CircleX,
  ClipboardList,
  Coins,
  Coffee,
  Copyright,
  CookingPot,
  Croissant,
  Dices,
  DollarSign,
  Dog,
  Edit,
  Euro,
  EyeOff,
  FileBarChart2,
  FilePenLine,
  FileText,
  Fish,
  FolderKanban,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Home,
  HousePlus,
  IceCreamCone,
  IndianRupee,
  Inbox,
  Info,
  JapaneseYen,
  KeyRound,
  Laptop,
  Landmark,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Mail,
  Map,
  MessageCircle,
  Milk,
  Monitor,
  Moon,
  Music,
  Nfc,
  Palette,
  PaperBag,
  PawPrint,
  Pencil,
  Percent,
  PiggyBank,
  Plane,
  Plug,
  Plus,
  Pizza,
  Popcorn,
  PoundSterling,
  QrCode,
  Refrigerator,
  Rocket,
  RotateCcw,
  Scale,
  Scissors,
  ScrollText,
  Search,
  SendHorizontal,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  SoapDispenserDroplet,
  Soup,
  Sparkles,
  Sprout,
  SquarePlay,
  Stethoscope,
  Store,
  SwissFranc,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Umbrella,
  Upload,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Vault,
  Wallet,
  WalletCards,
  Wine,
  Wrench,
} from 'lucide-react'

// Replacements for icons not present in lucide-react@1.28.0:
// - HouseKey -> KeyRound
// - Bottle   -> Milk
// - Broom    -> Brush
export interface CategoryIconProps {
  name?: string | null;
  size?: number | string;
  color?: string;
  strokeWidth?: number;
  className?: string;
  style?: React.CSSProperties;
  'aria-hidden'?: React.AriaAttributes['aria-hidden'];
}

const ICON_MAP: Record<string, React.ElementType> = {
  AlertTriangle,
  Apple,
  Archive,
  Armchair,
  ArrowDownFromLine,
  ArrowRightLeft,
  ArrowUpFromLine,
  Baby,
  Balloon,
  Banknote,
  BarChart3,
  Beef,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  BrushCleaning,
  Bug,
  Building2,
  CakeSlice,
  Calendar,
  Car,
  CarTaxiFront,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  Church,
  CircleDollarSign,
  CircleX,
  ClipboardList,
  Coins,
  Coffee,
  Copyright,
  CookingPot,
  Croissant,
  Dices,
  DollarSign,
  Dog,
  Edit,
  Euro,
  EyeOff,
  FileBarChart2,
  FilePenLine,
  FileText,
  Fish,
  FolderKanban,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  HeartHandshake,
  HeartPulse,
  Home,
  HousePlus,
  IceCreamCone,
  IndianRupee,
  Inbox,
  Info,
  JapaneseYen,
  KeyRound,
  Laptop,
  Landmark,
  Leaf,
  Lightbulb,
  LockKeyhole,
  Mail,
  Map,
  MessageCircle,
  Milk,
  Monitor,
  Moon,
  Music,
  Nfc,
  Palette,
  PaperBag,
  PawPrint,
  Pencil,
  Percent,
  PiggyBank,
  Plane,
  Plug,
  Plus,
  Pizza,
  Popcorn,
  PoundSterling,
  QrCode,
  Refrigerator,
  Rocket,
  RotateCcw,
  Scale,
  Scissors,
  ScrollText,
  Search,
  SendHorizontal,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  SoapDispenserDroplet,
  Soup,
  Sparkles,
  Sprout,
  SquarePlay,
  Stethoscope,
  Store,
  SwissFranc,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  Umbrella,
  Upload,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Vault,
  Wallet,
  WalletCards,
  Wine,
  Wrench,
}

export const LUCIDE_ICON_NAMES = [
  'AlertTriangle',
  'Archive',
  'Apple',
  'Armchair',
  'ArrowDownFromLine',
  'ArrowRightLeft',
  'ArrowUpFromLine',
  'Baby',
  'Balloon',
  'Banknote',
  'BarChart3',
  'Beef',
  'Beer',
  'Bike',
  'Bitcoin',
  'BookOpen',
  'BrainCircuit',
  'Briefcase',
  'BriefcaseBusiness',
  'Brush',
  'BrushCleaning',
  'Bug',
  'Building2',
  'CakeSlice',
  'Calendar',
  'Car',
  'CarTaxiFront',
  'ChartNoAxesCombined',
  'Check',
  'CheckCircle2',
  'Church',
  'CircleDollarSign',
  'CircleX',
  'ClipboardList',
  'Coins',
  'Coffee',
  'Copyright',
  'CookingPot',
  'Croissant',
  'Dices',
  'DollarSign',
  'Dog',
  'Edit',
  'Euro',
  'EyeOff',
  'FileBarChart2',
  'FilePenLine',
  'FileText',
  'Fish',
  'Gamepad2',
  'Gift',
  'GraduationCap',
  'HandCoins',
  'HandHeart',
  'HeartHandshake',
  'HeartPulse',
  'Home',
  'HousePlus',
  'IceCreamCone',
  'IndianRupee',
  'Info',
  'Inbox',
  'JapaneseYen',
  'KeyRound',
  'Laptop',

  'Landmark',
  'Leaf',
  'Lightbulb',
  'LockKeyhole',
  'Mail',
  'Map',
  'MessageCircle',
  'Milk',
  'Monitor',
  'Moon',
  'Music',
  'Nfc',
  'Palette',
  'PaperBag',
  'PawPrint',
  'Pencil',
  'Percent',
  'PiggyBank',
  'Plane',
  'Plug',
  'Plus',
  'Pizza',
  'Popcorn',
  'PoundSterling',
  'QrCode',
  'Refrigerator',
  'Rocket',
  'RotateCcw',
  'Scale',
  'Scissors',
  'ScrollText',
  'Search',
  'SendHorizontal',
  'Settings',
  'ShieldCheck',
  'Shirt',
  'ShoppingBag',
  'ShoppingCart',
  'Smartphone',
  'SoapDispenserDroplet',
  'Soup',
  'Sparkles',
  'Sprout',
  'SquarePlay',
  'Stethoscope',
  'Store',
  'SwissFranc',
  'Tag',
  'Target',
  'Trash2',
  'TrendingDown',
  'TrendingUp',
  'TriangleAlert',
  'Truck',
  'Umbrella',
  'Upload',
  'Users',
  'UsersRound',
  'Utensils',
  'UtensilsCrossed',
  'Vault',
  'Wallet',
  'WalletCards',
  'Wine',
  'Wrench',
]

const EMOJI_REGEX = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u

export function isLikelyLucideName(s: string | null | undefined): boolean {
  if (typeof s !== 'string') return false;
  if (s.trim() === '') return false;
  if (s.length < 2) return false; // single letter cannot be lucide name
  return /^[A-Z][A-Za-z0-9]+$/.test(s);
}

export function formatWalletIconForOption(icono: string | null | undefined): string {
  if (!icono || typeof icono !== 'string' || icono.trim() === '') return '💳';
  if (isLikelyLucideName(icono)) {
    return '💳';
  }
  return icono.trim();
}

export function CategoryIcon({
  name,
  size = 24,
  color,
  strokeWidth = 2,
  className,
  style,
  'aria-hidden': ariaHidden,
}: CategoryIconProps) {
  if (name === null || name === undefined || name.trim() === '') {
    return <Tag size={size} color={color} strokeWidth={strokeWidth} className={className} style={style} aria-hidden={ariaHidden} />;
  }

  // Trim the input for lookup
  const trimmedName = name.trim();

  if (isLikelyLucideName(trimmedName) && ICON_MAP[trimmedName]) {
    const Icon = ICON_MAP[trimmedName];
    return (
      <Icon
        size={size}
        color={color}
        strokeWidth={strokeWidth}
        className={className}
        style={style}
        aria-hidden={ariaHidden}
      />
    );
  }

  // Legacy letters and emoji values predate the shared Lucide icon map.
  if (/^[A-Z]$/.test(trimmedName) || EMOJI_REGEX.test(trimmedName)) {
    return (
      <span
        className={className}
        aria-hidden={ariaHidden}
        style={{
          fontSize: 'inherit',
          lineHeight: 1,
          ...style,
        }}
      >
        {trimmedName}
      </span>
    );
  }

  return <Tag size={size} color={color} strokeWidth={strokeWidth} className={className} style={style} aria-hidden={ariaHidden} />;
}



